#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Some constants for time-based calculations.
"""

SECONDS_IN_A_MINUTE = 60

MINUTES_IN_AN_HOUR = 60

SECONDS_IN_AN_HOUR = SECONDS_IN_A_MINUTE * MINUTES_IN_AN_HOUR

HOURS_IN_A_DAY = 24

SECONDS_IN_A_DAY = HOURS_IN_A_DAY * MINUTES_IN_AN_HOUR * SECONDS_IN_A_MINUTE

SECONDS_IN_A_WEEK = DAYS_IN_A_WEEK * HOURS_IN_A_DAY * MINUTES_IN_AN_HOUR * SECONDS_IN_A_MINUTE
